# Generated by Django 4.2.7 on 2025-09-21 06:18

import apps.reports.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsultationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinic_name", models.CharField(max_length=255)),
                (
                    "clinic_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.reports.models.logo_upload_path,
                    ),
                ),
                ("physician_name", models.CharField(max_length=255)),
                ("physician_contact", models.CharField(max_length=255)),
                ("patient_first_name", models.CharField(max_length=255)),
                ("patient_last_name", models.CharField(max_length=255)),
                ("patient_dob", models.DateField()),
                ("patient_contact", models.CharField(max_length=255)),
                (
                    "chief_complaint",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(5000)]
                    ),
                ),
                (
                    "consultation_note",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(5000)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consultation Report",
                "verbose_name_plural": "Consultation Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
